name: Build ARM64 Manual
on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push image to registry'
        required: false
        type: boolean
        default: false
      tag:
        description: 'Tag for the image (only used when push is true)'
        required: false
        type: string
        default: 'test-arm64'

jobs:
  build-debian-arm64:
    runs-on: ubuntu-24.04-arm  # Native ARM64 runner
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build Docker image
        uses: ./.github/actions/build/
        with:
          context: ./debian/
          platforms: linux/arm64
          load: ${{ !inputs.push }}
          push: ${{ inputs.push }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:${{ inputs.tag }}
      
      - name: Test ARM64 image (local build only)
        if: ${{ !inputs.push }}
        run: |
          echo "Testing ARM64 image locally..."
          docker run --rm ghcr.io/${{ github.repository_owner }}/texlive-ja-textlint:${{ inputs.tag }} \
            sh -c 'tex --version && tlmgr --version'